"""Repository functions for trading domain.

Standalone functions (no classes, no ABC, no inheritance).
Tortoise ORM handles connection pooling; use transactions for test isolation.

Each repository function operates on a single entity type and performs
data access only - no business logic.

Note:
    Tortoise handles connection pooling automatically. No explicit db
    parameter needed. Use transactions for test isolation.
"""

from datetime import datetime
from typing import Any

from stonks_trading.domains.trading.entities import (
    Genome,
    MarketData,
    Position,
    RiskEvent,
    Trade,
)
from stonks_trading.domains.trading.enums import Side
from stonks_trading.domains.trading.value_objects import Money, Symbol

# =============================================================================
# Trade Repository Functions
# =============================================================================


async def save_trade(trade: Trade) -> Trade:
    """Persist trade. Returns trade with assigned ID. No business logic.

    Uses Tortoise ORM which handles connection pooling automatically.

    Args:
        trade: Trade entity to save

    Returns:
        Trade with assigned ID
    """
    # In production, this would use Tortoise ORM:
    # from stonks_trading.shared.postgres_models import TradeModel
    # model = await TradeModel.create(
    #     symbol=trade.symbol.value,
    #     side=trade.side.value,
    #     fill_price=float(trade.fill_price),
    #     quantity=trade.quantity,
    #     fee=float(trade.fee),
    #     realized_pnl=float(trade.realized_pnl) if trade.realized_pnl else None,
    #     order_id=trade.order_id,
    #     venue_trade_id=trade.venue_trade_id,
    # )
    # trade.id = model.id

    # Stub implementation for Phase 1
    if trade.id is None:
        trade.id = 1  # Would be auto-generated by DB
    return trade


async def get_trade_by_id(trade_id: int) -> Trade | None:
    """Retrieve trade by ID. Returns None if not found."""
    # In production:
    # from stonks_trading.shared.postgres_models import TradeModel
    # model = await TradeModel.get_or_none(id=trade_id)
    # if not model:
    #     return None
    # return _model_to_trade_entity(model)
    return None  # Stub


async def list_trades_by_symbol(
    symbol: Symbol,
    start: datetime | None = None,
    end: datetime | None = None,
    limit: int = 100,
) -> list[Trade]:
    """List trades for symbol with optional date filter."""
    # In production:
    # from stonks_trading.shared.postgres_models import TradeModel
    # query = TradeModel.filter(symbol=symbol.value)
    # if start:
    #     query = query.filter(created_at__gte=start)
    # if end:
    #     query = query.filter(created_at__lte=end)
    # models = await query.limit(limit).order_by("-created_at")
    # return [_model_to_trade_entity(m) for m in models]
    return []  # Stub


async def list_trades(limit: int = 100, offset: int = 0) -> list[Trade]:
    """List all trades with pagination."""
    return []  # Stub


def _model_to_trade_entity(model: Any) -> Trade:
    """Internal helper: Convert DB model to domain entity (dataclass)."""
    return Trade(
        id=model.id,
        symbol=Symbol(value=model.symbol),
        side=Side(model.side),
        fill_price=Money(amount=model.fill_price, currency="USD"),
        quantity=model.quantity,
        fee=Money(amount=model.fee, currency="USD"),
        realized_pnl=Money(amount=model.realized_pnl, currency="USD")
        if model.realized_pnl
        else None,
        order_id=model.order_id,
        venue_trade_id=model.venue_trade_id,
        created_at=model.created_at,
    )


# =============================================================================
# Position Repository Functions
# =============================================================================


async def get_position_by_symbol(symbol: Symbol) -> Position | None:
    """Get open position for symbol. Returns None if no position."""
    return None  # Stub


async def save_position(position: Position) -> Position:
    """Save position. Creates new or updates existing."""
    if position.id is None:
        position.id = 1  # Would be auto-generated
    return position


async def close_position(symbol: Symbol) -> bool:
    """Close position for symbol (set quantity to 0). Returns success."""
    return True  # Stub


# =============================================================================
# Genome Repository Functions
# =============================================================================


async def save_genome(genome: Genome) -> Genome:
    """Persist genome with metadata. Returns genome with assigned ID."""
    if genome.id is None:
        genome.id = 1
    return genome


async def get_genome_by_id(genome_id: int) -> Genome | None:
    """Retrieve genome by ID."""
    return None  # Stub


async def get_active_genome(symbol: Symbol | None = None) -> Genome | None:
    """Get currently active genome for trading."""
    return None  # Stub


async def list_genomes(
    symbol: Symbol | None = None,
    limit: int = 100,
) -> list[Genome]:
    """List genomes with optional symbol filter."""
    return []  # Stub


async def activate_genome(genome_id: int) -> bool:
    """Activate genome for live trading. Deactivates others."""
    return True  # Stub


# =============================================================================
# Risk Event Repository Functions
# =============================================================================


async def save_risk_event(event: RiskEvent) -> RiskEvent:
    """Persist risk event for audit trail."""
    if event.id is None:
        event.id = 1
    return event


async def list_risk_events(
    severity: str | None = None,
    acknowledged: bool | None = None,
    limit: int = 100,
) -> list[RiskEvent]:
    """List risk events with filters."""
    return []  # Stub


async def acknowledge_risk_event(
    event_id: int,
    user: str,
    action: str | None = None,
) -> RiskEvent | None:
    """Mark risk event as acknowledged."""
    return None  # Stub


# =============================================================================
# Market Data Repository Functions
# =============================================================================


async def save_market_data(data: MarketData) -> MarketData:
    """Save market data candle."""
    return data


async def get_market_data(
    symbol: Symbol,
    start: datetime,
    end: datetime,
) -> list[MarketData]:
    """Get market data for date range."""
    return []  # Stub


async def get_latest_price(symbol: Symbol) -> float | None:
    """Get latest price for symbol."""
    return None  # Stub
